[env:um_tinys3]
platform = espressif32
board = um_tinys3
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.6.0
  bblanchon/ArduinoJson@^7.0.0
build_src_filter = +<main.cpp> -<usb_diagnostic.cpp>

[env:um_tinys3_diagnostic]
platform = espressif32
board = um_tinys3
framework = arduino
monitor_speed = 115200
build_src_filter = +<usb_diagnostic.cpp> -<main.cpp>

[env:gledopto_esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -DGLEDOPTO_ESP32
lib_deps = fastled/FastLED@^3.6.0
  bblanchon/ArduinoJson@^7.0.0
build_src_filter = +<main.cpp> -<usb_diagnostic.cpp>
